name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GAME_VERSION: FIRERED
      GAME_LANGUAGE: ENGLISH
      GAME_REVISION: 0
      MODERN: 0
      COMPARE: 0
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Checkout agbcc
        uses: actions/checkout@v2
        with:
          path: agbcc
          repository: kleeenexfeu/agbcc
          # originally going to pret/agbcc but I cloned it so

      - name: Install binutils
        run: sudo apt install gcc-arm-none-eabi binutils-arm-none-eabi
        # build-essential, git, and libpng-dev are already installed
        # gcc-arm-none-eabi is only needed for the modern build
        # as an alternative to dkP

      - name: Install agbcc
        run: |
          ./build.sh
          ./install.sh ../
        working-directory: ./agbcc

      - name: Build
        run: |
          make -j${nproc} all syms
        # don't -O to make it as close as possible from original

      - uses: actions/upload-artifact@v2
        with:
          name: pokefirered_built
          path: pokefirered.gba
          
      - uses: actions/upload-artifact@v2
        with:
          name: pokefirered_elf
          path: pokefirered.elf
          
      - uses: actions/upload-artifact@v2
        with:
          name: pokefirered_map
          path: pokefirered.map

      - uses: actions/upload-artifact@v2
        with:
          name: pokefirered_sym
          path: pokefirered.sym

